/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GrievanceContract } from "./GrievanceContract";
export * as factories from "./factories";
export { GrievanceContract__factory } from "./factories/GrievanceContract__factory";
